[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.97.2",
    "requests>=2.32.4",
    "urllib3>=2.5.0",
]
