[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "openai>=1.97.2",
    "requests-toolbelt>=1.0.0",
    "requests>=2.32.4",
    "urllib3>=2.5.0",
    "werkzeug>=3.1.3",
]
